steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'api/Dockerfile', '-t', '${_IMAGE_TAG}', '.']

images:
  - '${_IMAGE_TAG}'

substitutions:
  _IMAGE_TAG: 'us-central1-docker.pkg.dev/PROJECT_ID/uscis-api/uscis-api:latest'
